<?php

/**
 * @file
 *   Account Profile module
 *
 *
 * @developers:
 *    Rafal Wieczorek <kenorb@gmail.com>
 */

/**
 * Implementation of hook_menu().
 */
function account_profile_menu() { 
  $items = array();
  return $items;
}

/**
 * Implementation of hook_form_alter().
 */
function account_profile_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'profile_node_form':
      /* integration with account form */
      global $user;
      module_load_include('pages.inc', 'user');
      $account_form = user_profile_form(array(), $user);
      unset($account_form['submit'], $account_form['delete']); // remove duplicated Save button and Delete
      $form = array_merge($account_form, $form);
      $form['#validate'][] = 'account_profile_form_validate';
      $form['#submit'][] = 'account_profile_form_submit';
      $form['#submit'][] = 'account_profile_user_profile_submit';
    break;
    default:
  }
}

/**
 * Validation function for the user account and profile editing form.
 */
function account_profile_form_validate($form, &$form_state) {
  user_module_invoke('validate', $form_state['values'], $form_state['values']['_account'], $form_state['values']['_category']);
}

/**
 * Submit function for the user account and profile editing form.
 */
function account_profile_form_submit($form, &$form_state) {
  $account = $form_state['values']['_account'];
  $category = $form_state['values']['_category'];
  unset($form_state['values']['_account'], $form_state['values']['op'], $form_state['values']['submit'], $form_state['values']['delete'], $form_state['values']['form_token'], $form_state['values']['form_id'], $form_state['values']['_category']);
  user_module_invoke('submit', $form_state['values'], $account, $category);
  user_save($account, $form_state['values'], $category);

  // Clear the page cache because pages can contain usernames and/or profile information:
  cache_clear_all();

  drupal_set_message(t('The changes have been saved.'));
  return;
}

